#!/usr/bin/env bash
# In-container entrypoint: join the test cluster as a Node, then exec
# whatever CMD the task's docker-compose set (usually `sh -c sleep infinity`).
#
# Required env (passed in by the patched docker-compose):
#   TELEPORT_PROXY_ADDR     hostname:port the auth/proxy is reachable at
#                           from inside the docker network
#                           (e.g. tbench-fixture-auth:3025)
#   TELEPORT_JOIN_TOKEN     node-join token from `tctl tokens add --type=node`
#
# Optional:
#   TELEPORT_NODE_LABELS    comma-separated k=v list, stamped onto the Node
#                           so they appear on session.start audit events
#   T_BENCH_TASK_DOCKER_CLIENT_CONTAINER_NAME
#                           used as the nodename, which becomes the join key
#                           back to the task ID for harvest

set -euo pipefail

PROXY="${TELEPORT_PROXY_ADDR:-}"
TOKEN="${TELEPORT_JOIN_TOKEN:-}"
LABELS="${TELEPORT_NODE_LABELS:-}"
NODENAME_RAW="${T_BENCH_TASK_DOCKER_CLIENT_CONTAINER_NAME:-$(hostname)}"
# Teleport nodenames must satisfy DNS-1123: lowercase alphanumerics and
# hyphens only. Terminal-Bench's container names use `__` as a separator
# (e.g. hello-world-1-of-1-2026-04-25__16-07-20) which Teleport rejects,
# falling back to a random UUID and breaking `tsh ssh agent@<name>`.
# Squash any non-conforming chars to `-` and lowercase.
NODENAME="$(echo "$NODENAME_RAW" | tr '[:upper:]_' '[:lower:]-' | tr -cs 'a-z0-9-' '-' | sed 's/-\+/-/g; s/^-//; s/-$//')"

if [[ -z "$PROXY" || -z "$TOKEN" ]]; then
  echo "[tbench-teleport-entry] no TELEPORT_PROXY_ADDR/TOKEN; skipping node start" >&2
  exec "$@"
fi

mkdir -p /var/lib/teleport-node /var/log
chown -R agent:agent /var/lib/teleport-node

cat > /etc/teleport.yaml <<EOF
version: v3
teleport:
  nodename: ${NODENAME}
  data_dir: /var/lib/teleport-node
  auth_token: ${TOKEN}
  auth_server: ${PROXY}
  log:
    severity: INFO
    output: /var/log/teleport.log
auth_service:
  enabled: false
proxy_service:
  enabled: false
ssh_service:
  enabled: true
EOF

if [[ -n "$LABELS" ]]; then
  echo "  labels:" >> /etc/teleport.yaml
  IFS=',' read -ra pairs <<< "$LABELS"
  for kv in "${pairs[@]}"; do
    key="${kv%%=*}"
    val="${kv#*=}"
    printf '    "%s": "%s"\n' "$key" "$val" >> /etc/teleport.yaml
  done
fi

# Background the node. Logs go to /var/log/teleport.log inside the
# container; harvest.py can pull them on failure.
nohup teleport start -c /etc/teleport.yaml --insecure >/dev/null 2>&1 &
echo "[tbench-teleport-entry] teleport node started, nodename=${NODENAME}" >&2

# Persist task env + WORKDIR so `tsh ssh` shells match `docker exec`
# behaviour. `docker exec` inherits the container's env and WORKDIR;
# SSH does not (sshd only preserves a tiny env whitelist, and shells
# start in $HOME instead of the image's WORKDIR). Many Terminal-Bench
# tasks rely on the python-3-13 base setting WORKDIR=/app — their
# solution.sh files write to relative paths like `hello.txt` that
# silently land in the wrong place under SSH.
TBENCH_INIT=/etc/tbench-env.sh
{
  echo "# Generated by tbench-teleport-entry"
  for var in TEST_DIR TELEPORT_PROXY_ADDR TELEPORT_NODE_LABELS \
             T_BENCH_TASK_DOCKER_CLIENT_CONTAINER_NAME; do
    val="$(eval "echo \${$var:-}")"
    if [[ -n "$val" ]]; then
      printf 'export %s=%q\n' "$var" "$val"
    fi
  done
  # Match the python-3-13 base image's WORKDIR.
  echo 'cd /app 2>/dev/null || true'
} > "$TBENCH_INIT"
chmod 0644 "$TBENCH_INIT"

# Source $TBENCH_INIT from every shell entry point we can plausibly
# hit: profile.d for login shells, /etc/bash.bashrc for non-login
# interactive shells (Debian default), and ~/.bashrc for both root
# and agent home dirs as a belt-and-braces.
ln -sf "$TBENCH_INIT" /etc/profile.d/tbench-env.sh
grep -q "$TBENCH_INIT" /etc/bash.bashrc 2>/dev/null \
  || echo "source $TBENCH_INIT" >> /etc/bash.bashrc
for home in /root /home/agent; do
  mkdir -p "$home"
  grep -q "$TBENCH_INIT" "$home/.bashrc" 2>/dev/null \
    || echo "source $TBENCH_INIT" >> "$home/.bashrc"
done
chown -R agent:agent /home/agent

# Brief wait so the very first `_exec_run` from the harness doesn't race
# the node-join handshake. The runner's TshTerminal also retries on
# transient failures, so this is best-effort.
sleep 3

exec "$@"
